sudo: required
services:
  - docker

before_install:
  - docker build -t geobako/docker-react-deploy-test -f Dockerfile.dev .

script:
  - docker run geobako/docker-react-deploy-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-deploy-test"
  env: "DockerReactDeployTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-849845598606"
  bucket_path: "docker-react-deploy-test"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"