sudo: required
services:
  - docker

before_install:
  - docker build -t geobako/docker-react-deploy-test -f Dockerfile.dev .

script:
  - docker run geobako/docker-react-deploy-test npm run test -- --coverage